{% set name = "librabbitmq" %}
{% set version = "2.0.0" %}
{% set compress_type = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_val = "ffa2363a860ab5dcc3ce3703247e05e940c73d776c03a3f3f9deaf3cf43bb96c" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash_val }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - toolchain

  run:
    - python
    - toolchain
    - amqp >=1.4.6
    - six >=1.0.0

test:
  imports:
    - funtests
    - funtests.tests
    - librabbitmq
    - librabbitmq.tests

about:
  home: http://github.com/celery/librabbitmq
  license: MPL 1.1
  license_file: LICENSE-MPL-RabbitMQ
  summary: 'AMQP Client using the rabbitmq-c library.'

extra:
  recipe-maintainers:
    - pmlandwehr
    - anguslees
