{% set name = "librabbitmq" %}
{% set version = "1.6.1" %}
{% set compress_type = "tar.gz" %}
{% set sha256 = "604a226b9fe3f9e439353702a731f2a39cf771882e68bca020cb224d9b990c49" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  sha256: {{ sha256 }}

build:
  skip: True  # [win or py3k]
  number: 1001
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
  run:
    - python
    - amqp >=1.4.6

test:
  imports:
    - funtests
    - funtests.tests
    - librabbitmq
    - librabbitmq.tests

about:
  home: http://github.com/celery/librabbitmq
  license: MPL 1.1
  license_file: LICENSE-MPL-RabbitMQ
  summary: 'AMQP Client using the rabbitmq-c library.'

extra:
  recipe-maintainers:
    - pmlandwehr
    - anguslees
