# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python2.7

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "mzcpgTvQDEndZ/Ll+QWCq2DFg8IbmxxjzlZImqst1r2IhvVhirbqoxh/nnSXVcvd63GD1PXZo3b9tFwmCSg8MuahJxCx5MQO7wZRNQVN4P3vLn3jL5hTIuh0WGbB6XPjLS1bvIXWk7BwXV9C1eTrMd+7HJY8o9kjcHVcFM+iMzz19z3y4nL3EFlFEQOCzFqGbW5tlbGQFqTJw0osKMdvMBHpCVnEt9/xjIluYvquy0bolQNtQgCVMHtOUdmZSDwZsahroFDeEn4tLhNJKs3XQ4GhCFxpSPWYET2pg56l0/F3r/tXOtjK4yogVhCcI0DtUX262vqrCw9R3jcYvXpKlFW9Gy8vqhr8MNI1kedH1zKYn3NnikfnFvWi74Ia+yvZR+N53z4ujG3vCmz2aKawd5GqXBMLzhVCTnQ1qhGEd28s++k0xykRXn1sd10LYmkOEYoc/7cxEXA9iG1WVllHI2dabSv28U83xhpDIgI8vtHc5odizOhtsNicIgRX8ziucE9NThWEZKDtdkcQeJq/eDhhZEF9f7CUjcYnH27DjJ4qXSd0h4ixXnTgchh3DLgNSoggXZhYjBS6Wxa4XYe9jM9fZhRmgwU+EdS4UMqmyhc3i8aRJtDM2zIf47Ia6uSZyv8u/zCxPfR2jt2cMLKhUWnhjPB5KYZYDy6iAnBcS1w="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
