appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: mzcpgTvQDEndZ/Ll+QWCq2DFg8IbmxxjzlZImqst1r2IhvVhirbqoxh/nnSXVcvd63GD1PXZo3b9tFwmCSg8MuahJxCx5MQO7wZRNQVN4P3vLn3jL5hTIuh0WGbB6XPjLS1bvIXWk7BwXV9C1eTrMd+7HJY8o9kjcHVcFM+iMzz19z3y4nL3EFlFEQOCzFqGbW5tlbGQFqTJw0osKMdvMBHpCVnEt9/xjIluYvquy0bolQNtQgCVMHtOUdmZSDwZsahroFDeEn4tLhNJKs3XQ4GhCFxpSPWYET2pg56l0/F3r/tXOtjK4yogVhCcI0DtUX262vqrCw9R3jcYvXpKlFW9Gy8vqhr8MNI1kedH1zKYn3NnikfnFvWi74Ia+yvZR+N53z4ujG3vCmz2aKawd5GqXBMLzhVCTnQ1qhGEd28s++k0xykRXn1sd10LYmkOEYoc/7cxEXA9iG1WVllHI2dabSv28U83xhpDIgI8vtHc5odizOhtsNicIgRX8ziucE9NThWEZKDtdkcQeJq/eDhhZEF9f7CUjcYnH27DjJ4qXSd0h4ixXnTgchh3DLgNSoggXZhYjBS6Wxa4XYe9jM9fZhRmgwU+EdS4UMqmyhc3i8aRJtDM2zIf47Ia6uSZyv8u/zCxPfR2jt2cMLKhUWnhjPB5KYZYDy6iAnBcS1w=}
